version: '3'

services:
  kasa-service:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "4000:4000"
    networks:
      - local

networks:
  local:
    driver: bridge
